# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'autotest.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QLineEdit,
    QPlainTextEdit, QPushButton, QRadioButton, QSizePolicy,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(928, 808)
        self.testlog = QPlainTextEdit(Form)
        self.testlog.setObjectName(u"testlog")
        self.testlog.setGeometry(QRect(430, 20, 481, 771))
        self.testlog.setReadOnly(True)
        self.main_com_box = QGroupBox(Form)
        self.main_com_box.setObjectName(u"main_com_box")
        self.main_com_box.setGeometry(QRect(10, 30, 371, 151))
        self.Serial = QRadioButton(self.main_com_box)
        self.Serial.setObjectName(u"Serial")
        self.Serial.setGeometry(QRect(270, 60, 61, 20))
        self.Telnet = QRadioButton(self.main_com_box)
        self.Telnet.setObjectName(u"Telnet")
        self.Telnet.setGeometry(QRect(270, 90, 61, 20))
        self.ssh = QRadioButton(self.main_com_box)
        self.ssh.setObjectName(u"ssh")
        self.ssh.setGeometry(QRect(270, 30, 61, 20))
        self.com_ip = QLabel(self.main_com_box)
        self.com_ip.setObjectName(u"com_ip")
        self.com_ip.setGeometry(QRect(20, 30, 54, 16))
        self.user = QLabel(self.main_com_box)
        self.user.setObjectName(u"user")
        self.user.setGeometry(QRect(20, 50, 54, 16))
        self.password = QLabel(self.main_com_box)
        self.password.setObjectName(u"password")
        self.password.setGeometry(QRect(20, 70, 54, 16))
        self.Baud = QLabel(self.main_com_box)
        self.Baud.setObjectName(u"Baud")
        self.Baud.setGeometry(QRect(20, 90, 54, 16))
        self.COM = QLabel(self.main_com_box)
        self.COM.setObjectName(u"COM")
        self.COM.setGeometry(QRect(20, 110, 54, 16))
        self.com_ip_text = QLineEdit(self.main_com_box)
        self.com_ip_text.setObjectName(u"com_ip_text")
        self.com_ip_text.setGeometry(QRect(100, 30, 141, 20))
        self.com_user_text = QLineEdit(self.main_com_box)
        self.com_user_text.setObjectName(u"com_user_text")
        self.com_user_text.setGeometry(QRect(100, 50, 141, 20))
        self.baud_text = QLineEdit(self.main_com_box)
        self.baud_text.setObjectName(u"baud_text")
        self.baud_text.setGeometry(QRect(100, 90, 141, 20))
        self.com_pass_text = QLineEdit(self.main_com_box)
        self.com_pass_text.setObjectName(u"com_pass_text")
        self.com_pass_text.setGeometry(QRect(100, 70, 141, 20))
        self.com_text = QLineEdit(self.main_com_box)
        self.com_text.setObjectName(u"com_text")
        self.com_text.setGeometry(QRect(100, 110, 141, 20))
        self.other_com_box = QGroupBox(Form)
        self.other_com_box.setObjectName(u"other_com_box")
        self.other_com_box.setGeometry(QRect(10, 190, 371, 161))
        self.bmc_ip = QLabel(self.other_com_box)
        self.bmc_ip.setObjectName(u"bmc_ip")
        self.bmc_ip.setGeometry(QRect(20, 20, 54, 16))
        self.bmc_user = QLabel(self.other_com_box)
        self.bmc_user.setObjectName(u"bmc_user")
        self.bmc_user.setGeometry(QRect(20, 40, 61, 16))
        self.os_ip = QLabel(self.other_com_box)
        self.os_ip.setObjectName(u"os_ip")
        self.os_ip.setGeometry(QRect(20, 80, 54, 16))
        self.BMC = QRadioButton(self.other_com_box)
        self.BMC.setObjectName(u"BMC")
        self.BMC.setGeometry(QRect(270, 20, 61, 20))
        self.OS = QRadioButton(self.other_com_box)
        self.OS.setObjectName(u"OS")
        self.OS.setGeometry(QRect(270, 50, 61, 20))
        self.bmc_pass = QLabel(self.other_com_box)
        self.bmc_pass.setObjectName(u"bmc_pass")
        self.bmc_pass.setGeometry(QRect(20, 60, 61, 16))
        self.os_user = QLabel(self.other_com_box)
        self.os_user.setObjectName(u"os_user")
        self.os_user.setGeometry(QRect(20, 100, 54, 16))
        self.os_pass = QLabel(self.other_com_box)
        self.os_pass.setObjectName(u"os_pass")
        self.os_pass.setGeometry(QRect(20, 120, 54, 16))
        self.bmc_ip_text = QLineEdit(self.other_com_box)
        self.bmc_ip_text.setObjectName(u"bmc_ip_text")
        self.bmc_ip_text.setGeometry(QRect(100, 20, 141, 20))
        self.bmc_user_text = QLineEdit(self.other_com_box)
        self.bmc_user_text.setObjectName(u"bmc_user_text")
        self.bmc_user_text.setGeometry(QRect(100, 40, 141, 20))
        self.bmc_pass_text = QLineEdit(self.other_com_box)
        self.bmc_pass_text.setObjectName(u"bmc_pass_text")
        self.bmc_pass_text.setGeometry(QRect(100, 60, 141, 20))
        self.os_ip_text = QLineEdit(self.other_com_box)
        self.os_ip_text.setObjectName(u"os_ip_text")
        self.os_ip_text.setGeometry(QRect(100, 80, 141, 20))
        self.os_user_text = QLineEdit(self.other_com_box)
        self.os_user_text.setObjectName(u"os_user_text")
        self.os_user_text.setGeometry(QRect(100, 100, 141, 20))
        self.os_pass_text = QLineEdit(self.other_com_box)
        self.os_pass_text.setObjectName(u"os_pass_text")
        self.os_pass_text.setGeometry(QRect(100, 120, 141, 20))
        self.testlog_box = QGroupBox(Form)
        self.testlog_box.setObjectName(u"testlog_box")
        self.testlog_box.setGeometry(QRect(10, 730, 371, 51))
        self.execute_box = QGroupBox(Form)
        self.execute_box.setObjectName(u"execute_box")
        self.execute_box.setGeometry(QRect(10, 660, 371, 61))
        self.start = QPushButton(self.execute_box)
        self.start.setObjectName(u"start")
        self.start.setGeometry(QRect(10, 20, 75, 24))
        self.Pause = QPushButton(self.execute_box)
        self.Pause.setObjectName(u"Pause")
        self.Pause.setGeometry(QRect(140, 20, 75, 24))
        self.end = QPushButton(self.execute_box)
        self.end.setObjectName(u"end")
        self.end.setGeometry(QRect(270, 20, 75, 24))
        self.test_type = QGroupBox(Form)
        self.test_type.setObjectName(u"test_type")
        self.test_type.setGeometry(QRect(10, 370, 171, 211))
        self.reboot_test = QRadioButton(self.test_type)
        self.reboot_test.setObjectName(u"reboot_test")
        self.reboot_test.setGeometry(QRect(20, 30, 111, 20))
        self.dc_test = QRadioButton(self.test_type)
        self.dc_test.setObjectName(u"dc_test")
        self.dc_test.setGeometry(QRect(20, 60, 111, 20))
        self.ac_test = QRadioButton(self.test_type)
        self.ac_test.setObjectName(u"ac_test")
        self.ac_test.setGeometry(QRect(20, 90, 111, 20))
        self.up_dowm_test = QRadioButton(self.test_type)
        self.up_dowm_test.setObjectName(u"up_dowm_test")
        self.up_dowm_test.setGeometry(QRect(20, 120, 111, 20))
        self.test_num = QGroupBox(Form)
        self.test_num.setObjectName(u"test_num")
        self.test_num.setGeometry(QRect(10, 590, 371, 61))
        self.num = QLabel(self.test_num)
        self.num.setObjectName(u"num")
        self.num.setGeometry(QRect(20, 30, 81, 16))
        self.num_text = QLineEdit(self.test_num)
        self.num_text.setObjectName(u"num_text")
        self.num_text.setGeometry(QRect(110, 30, 141, 20))
        self.test_command = QGroupBox(Form)
        self.test_command.setObjectName(u"test_command")
        self.test_command.setGeometry(QRect(210, 370, 171, 211))
        self.basic_function = QRadioButton(self.test_command)
        self.basic_function.setObjectName(u"basic_function")
        self.basic_function.setGeometry(QRect(20, 30, 111, 20))
        self.aging_test = QRadioButton(self.test_command)
        self.aging_test.setObjectName(u"aging_test")
        self.aging_test.setGeometry(QRect(20, 60, 111, 20))
        self.all_comm = QRadioButton(self.test_command)
        self.all_comm.setObjectName(u"all_comm")
        self.all_comm.setGeometry(QRect(20, 90, 111, 20))
        self.custom_comm = QRadioButton(self.test_command)
        self.custom_comm.setObjectName(u"custom_comm")
        self.custom_comm.setGeometry(QRect(20, 120, 111, 20))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"\u81ea\u52a8\u5316\u6d4b\u8bd5\u5de5\u5177", None))
        self.testlog.setPlaceholderText(QCoreApplication.translate("Form", u"\u6d4b\u8bd5\u65e5\u5fd7\u8f93", None))
        self.main_com_box.setTitle(QCoreApplication.translate("Form", u"\u4e32\u53e3\u53c2\u6570", None))
        self.Serial.setText(QCoreApplication.translate("Form", u"Serial", None))
        self.Telnet.setText(QCoreApplication.translate("Form", u"Telnet", None))
        self.ssh.setText(QCoreApplication.translate("Form", u"SSH", None))
        self.com_ip.setText(QCoreApplication.translate("Form", u"IP\u5730\u5740", None))
        self.user.setText(QCoreApplication.translate("Form", u"\u8d26\u53f7", None))
        self.password.setText(QCoreApplication.translate("Form", u"\u5bc6\u7801", None))
        self.Baud.setText(QCoreApplication.translate("Form", u"\u6ce2\u7279\u7387", None))
        self.COM.setText(QCoreApplication.translate("Form", u"COM", None))
        self.other_com_box.setTitle(QCoreApplication.translate("Form", u"\u5176\u4ed6\u53c2\u6570", None))
        self.bmc_ip.setText(QCoreApplication.translate("Form", u"BMC_IP", None))
        self.bmc_user.setText(QCoreApplication.translate("Form", u"BMC_\u8d26\u53f7", None))
        self.os_ip.setText(QCoreApplication.translate("Form", u"OS_IP", None))
        self.BMC.setText(QCoreApplication.translate("Form", u"BMC", None))
        self.OS.setText(QCoreApplication.translate("Form", u"OS", None))
        self.bmc_pass.setText(QCoreApplication.translate("Form", u"BMC_\u5bc6\u7801", None))
        self.os_user.setText(QCoreApplication.translate("Form", u"OS_\u8d26\u53f7", None))
        self.os_pass.setText(QCoreApplication.translate("Form", u"OS_\u5bc6\u7801", None))
        self.testlog_box.setTitle(QCoreApplication.translate("Form", u"\u6d4b\u8bd5\u65e5\u5fd7\u8def\u5f84", None))
        self.execute_box.setTitle(QCoreApplication.translate("Form", u"\u6267\u884c\u6309\u94ae", None))
        self.start.setText(QCoreApplication.translate("Form", u"\u5f00\u59cb\u6d4b\u8bd5", None))
        self.Pause.setText(QCoreApplication.translate("Form", u"\u6682\u505c\u6d4b\u8bd5", None))
        self.end.setText(QCoreApplication.translate("Form", u"\u7ed3\u675f\u6d4b\u8bd5", None))
        self.test_type.setTitle(QCoreApplication.translate("Form", u"\u6d4b\u8bd5\u7c7b\u578b", None))
        self.reboot_test.setText(QCoreApplication.translate("Form", u"Reboot\u6d4b\u8bd5", None))
        self.dc_test.setText(QCoreApplication.translate("Form", u"DC\u6d4b\u8bd5", None))
        self.ac_test.setText(QCoreApplication.translate("Form", u"AC\u6d4b\u8bd5", None))
        self.up_dowm_test.setText(QCoreApplication.translate("Form", u"\u5347\u7ea7\u7ea7\u6d4b\u8bd5", None))
        self.test_num.setTitle(QCoreApplication.translate("Form", u"\u6d4b\u8bd5\u6b21\u6570", None))
        self.num.setText(QCoreApplication.translate("Form", u"\u8f93\u5165\u6d4b\u8bd5\u6b21\u6570", None))
        self.test_command.setTitle(QCoreApplication.translate("Form", u"\u6d4b\u8bd5\u547d\u4ee4", None))
        self.basic_function.setText(QCoreApplication.translate("Form", u"\u57fa\u7840\u529f\u80fd", None))
        self.aging_test.setText(QCoreApplication.translate("Form", u"\u8001\u5316\u6d4b\u8bd5", None))
        self.all_comm.setText(QCoreApplication.translate("Form", u"\u5168\u8986\u76d6\u547d\u4ee4", None))
        self.custom_comm.setText(QCoreApplication.translate("Form", u"\u81ea\u5b9a\u4e49\u547d\u4ee4\u96c6", None))
    # retranslateUi

